import { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { getPrediction } from "../api/diagnosticApi";

const uncertaintyColors = {
  Low: { bg: "#dcfce7", text: "#166534", border: "#86efac" },
  Medium: { bg: "#fff7ed", text: "#9a3412", border: "#fdba74" },
  High: { bg: "#fef2f2", text: "#991b1b", border: "#fca5a5" },
};

const statusColors = {
  true: { bg: "#eff6ff", text: "#1e40af", border: "#93c5fd" },
  false: { bg: "#f9fafb", text: "#6b7280", border: "#e5e7eb" },
};

export default function PredictionDetail() {
  const { id } = useParams();
  const { token, logout } = useAuth();
  const navigate = useNavigate();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    getPrediction(id, token)
      .then((result) => setData(result))
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false));
  }, [id, token]);

  if (loading) {
    return (
      <div className="dashboard-root">
        <div className="empty-state" style={{ minHeight: "100vh" }}>
          <div className="spinner-large" />
          <p className="empty-title">Loading prediction...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="dashboard-root">
        <div className="empty-state" style={{ minHeight: "100vh" }}>
          <p className="empty-title">Error: {error}</p>
          <button className="nav-btn" onClick={() => navigate("/home")} style={{ marginTop: 16 }}>
            Back to Home
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="dashboard-root">
      <header className="dash-header">
        <div className="dash-header-inner">
          <div className="dash-header-left">
            <div className="dash-logo-icon">
              <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#2563eb" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <path d="M22 12h-4l-3 9L9 3l-3 9H2" />
              </svg>
            </div>
            <div>
              <h1 className="dash-header-title">Prediction Detail</h1>
              <p className="dash-header-subtitle">
                {data.patient.first_name} {data.patient.last_name} (MRN: {data.patient.mrn})
              </p>
            </div>
          </div>
          <div className="dash-header-right">
            <button className="nav-btn nav-icon-btn" onClick={() => navigate("/home")} title="Home">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z" />
                <polyline points="9 22 9 12 15 12 15 22" />
              </svg>
            </button>
            <button className="nav-btn logout-btn" onClick={logout}>Logout</button>
          </div>
        </div>
      </header>

      <main className="dash-main">
        <div className="dash-grid">
          <section className="panel">
            <div className="panel-header">
              <div>
                <h2 className="panel-title">Chest X-ray</h2>
                <p className="panel-subtitle">
                  {data.patient.first_name} {data.patient.last_name} - {new Date(data.created_at).toLocaleString()}
                </p>
              </div>
            </div>
            <div className="panel-body">
              <div className="image-container">
                <img
                  src={data.image_path}
                  alt="Chest X-ray"
                  className="xray-image"
                />
              </div>
            </div>
          </section>

          <section className="panel">
            <div className="panel-header">
              <div className="results-header">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#2563eb" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <circle cx="12" cy="12" r="10" />
                  <line x1="12" y1="16" x2="12" y2="12" />
                  <line x1="12" y1="8" x2="12.01" y2="8" />
                </svg>
                <div>
                  <h2 className="panel-title">Model Predictions and Uncertainty</h2>
                  <p className="panel-subtitle">Prediction set generated by the diagnostic support model</p>
                </div>
              </div>
            </div>

            <div className="panel-body">
              <div className="results-container">
                <div className="summary-row">
                  <div className="summary-card">
                    <p className="summary-label">
                      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#2563eb" strokeWidth="2">
                        <polyline points="23 6 13.5 15.5 8.5 10.5 1 18" />
                        <polyline points="17 6 23 6 23 12" />
                      </svg>
                      Top Predicted Finding
                    </p>
                    <p className="summary-value">
                      {data.top_finding}
                      <span className="summary-prob">({data.top_probability.toFixed(2)})</span>
                    </p>
                  </div>

                  <div className="summary-card">
                    <p className="summary-label">
                      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#059669" strokeWidth="2">
                        <path d="M22 11.08V12a10 10 0 11-5.93-9.14" />
                        <polyline points="22 4 12 14.01 9 11.01" />
                      </svg>
                      Prediction Set Size
                    </p>
                    <p className="summary-value">
                      {data.prediction_set_size} labels
                      <span className="coverage-value">at {data.coverage} coverage</span>
                    </p>
                  </div>
                </div>

                <div className="table-section">
                  <p className="table-title">All Findings</p>
                  <div className="table-header">
                    <span className="col-finding">Finding</span>
                    <span className="col-centered">Probability</span>
                    <span className="col-centered">Uncertainty</span>
                    <span className="col-centered">Status</span>
                  </div>

                  {data.findings.map((findingRow, index) => {
                    const uncertaintyPalette = uncertaintyColors[findingRow.uncertainty];
                    const statusPalette = statusColors[findingRow.in_prediction_set.toString()];

                    return (
                      <div
                        key={findingRow.finding}
                        className={`table-row ${findingRow.in_prediction_set ? "in-set" : ""}`}
                        style={{ animationDelay: `${index * 80}ms` }}
                      >
                        <span className="col-finding finding-name">{findingRow.finding}</span>
                        <span className="col-centered">
                          <span className="prob-value">{findingRow.probability.toFixed(2)}</span>
                        </span>
                        <span className="col-centered">
                          <span
                            className="badge"
                            style={{
                              backgroundColor: uncertaintyPalette.bg,
                              color: uncertaintyPalette.text,
                              borderColor: uncertaintyPalette.border,
                            }}
                          >
                            {findingRow.uncertainty}
                          </span>
                        </span>
                        <span className="col-centered">
                          <span
                            className="badge"
                            style={{
                              backgroundColor: statusPalette.bg,
                              color: statusPalette.text,
                              borderColor: statusPalette.border,
                              fontWeight: findingRow.in_prediction_set ? 600 : 400,
                            }}
                          >
                            {findingRow.in_prediction_set ? "In prediction set" : "Not in set"}
                          </span>
                        </span>
                      </div>
                    );
                  })}
                </div>

                <div className="note-box">
                  <p className="note-text">
                    <strong>Note:</strong> Findings marked &quot;In prediction set&quot; have a &gt;{data.coverage} chance of containing the true diagnosis.
                    Lower uncertainty indicates higher model confidence. Threshold (lamhat) = {data.lamhat.toFixed(4)}.
                  </p>
                </div>

                <div className="tech-details">
                  <p className="tech-title">Technical Details</p>
                  <div className="tech-grid">
                    <div>
                      <span className="tech-label">alpha (risk level)</span>
                      <span className="tech-value">{data.alpha}</span>
                    </div>
                    <div>
                      <span className="tech-label">lamhat (threshold)</span>
                      <span className="tech-value">{data.lamhat.toFixed(6)}</span>
                    </div>
                    <div>
                      <span className="tech-label">Coverage</span>
                      <span className="tech-value">{data.coverage}</span>
                    </div>
                    <div>
                      <span className="tech-label">Set size</span>
                      <span className="tech-value">{data.prediction_set_size} / 5</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </main>
    </div>
  );
}
